
clc
clear
close all

env_paths = getappdata(0, "env_paths");
model = getappdata(0, "model");
params = getappdata(0, "params");
input_db = getappdata(0, "input_db");
dates = getappdata(0, "dates");
timestamp = getappdata(0, "timestamp");

rehash path
apply_new_judgment_func = @apply_new_judgment;

[reference_db, final_db] = modeler.run_forecast( ...
    model, ...
    params, ...
    input_db, ...
    dates, ...
    apply_new_judgment_func ...
);

data_column = 1;
output_response = modeler.prepare_country_output_data( ...
    final_db, ...
    env_paths.output_mapping_path, ...
    env_paths.output_data_path, ...
    data_column, ...
    timestamp ...
);

