name: Call reusable workflow

on:
    workflow_dispatch:


jobs:
    run-reusable:
        uses: ./.github/workflows/subflow.yml

    call-and-modify:
        runs-on: ubuntu-latest
        needs: run-reusable

        steps:

            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: art
                path: subf

            - name: Add to file
              run: |
                ls
                echo 456 > file456.txt
                cat subf/file123.txt file456.txt > file.txt

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: end
                path: file.txt
