name: Create pull request

permissions:
    actions: write

on:
  push:
    branches:
      - 'forecast-*-ANALYST'
jobs:
    create_pull_request:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ github.token }}
        steps:
            - name: Clone country model repo
              uses: actions/checkout@v3
              with:
                ref: ${{ github.ref }}

            - name: get target branch name removing "-ANALYST"
              id: get_branch_name
              run: |
                echo "branch_name=$(echo ${{ github.ref }} | sed 's/-ANALYST//g')" >> $GITHUB_OUTPUT

            - name: Create pull request to target branch using gh cli
              run: |
                gh pr create --title "Merging ${{ github.ref }}" --body "Merging ${{ github.ref }} to ${{ steps.get_branch_name.outputs.branch_name }}" --base ${{ steps.get_branch_name.outputs.branch_name }} --head ${{ github.ref }}
