name: Call reusable workflow

on:
    workflow_dispatch:


jobs:
    run-reusable:
        uses: ./.github/workflows/subflow.yml

    call-and-modify:
        runs-on: ubuntu-latest
        needs: run-reusable

        steps:

            - name: Download artifact
              uses: actions/download-artifact@v3
                  with:
                      name: art
