name: Prepare forecast environment

permissions:
    actions: write

on:
    workflow_dispatch:
        inputs:
            model_repo:
                description: "Country model repo"
                required: true
                type: choice
                options:
                    - "Model-EA"
                    - "Model-US"
                    - "Model-CZ"
            model_repo_ref:
                description: "Country model version"
                required: false
                type: string
                default: ""
            input_data_snapshot_time:
                description: "Input data snapshot time"
                required: false
                type: string
                default: ""
            model_infra_repo_ref:
                description: "Model infrastructure version"
                required: false
                type: string
                default: ""
            toolset_repo_ref:
                description: "Toolset version"
                required: false
                type: string
                default: ""
            data_warehouse_client_repo_ref:
                description: "Data warehouse client version"
                required: false
                type: string
                default: ""
            iris_repo_ref:
                description: "Iris toolbox version"
                required: false
                type: string
                default: ""

jobs:

    prepare_local_environment_artifact:

        runs-on: ubuntu-latest

        env:
            CI_AUTHOR: "Production workflow"
            CI_EMAIL: "noreply@ogresearch.com"
            WORKFLOW_FORECAST_REPO: "workflow-forecast"
            MODEL_REPO: "model"
            MODEL_INFRA_REPO: "model-infra"
            TOOLSET_REPO: "toolset"
            DATA_WAREHOUSE_CLIENT_REPO: "data-warehouse-client"
            IRIS_TOOLBOX_REPO: "iris-toolbox"

        steps:

            - name: Clone country model repo
              uses: actions/checkout@v3
              with:
                  repository: OGR-EIU/${{ inputs.model_repo }}
                  ref: ${{ inputs.model_repo_ref }}
                  fetch-depth: 1
                  path: ./${{ env.MODEL_REPO }}
                  token: ${{ secrets.token_with_all_access }}


            - name: Clone model infra repo
              uses: actions/checkout@v3
              with:
                  repository: OGR-EIU/${{ env.MODEL_INFRA_REPO }}
                  ref: ${{ inputs.model_infra_repo_ref }}
                  fetch-depth: 1
                  path: ./${{ env.MODEL_INFRA_REPO }}
                  token: ${{ secrets.token_with_all_access }}


            - name: Clone toolset repo
              uses: actions/checkout@v3
              with:
                  repository: OGR-EIU/toolset
                  ref: ${{ inputs.toolset_repo_ref }}
                  fetch-depth: 1
                  path: ./toolset
                  token: ${{ secrets.token_with_all_access }}


            - name: Clone data warehouse client repo
              uses: actions/checkout@v3
              with:
                  repository: OGR-EIU/data-warehouse-client
                  ref: ${{ inputs.data_warehouse_client_repo_ref }}
                  fetch-depth: 1
                  path: ./data-warehouse-client
                  token: ${{ secrets.token_with_all_access }}


            - name: Clone Iris toolbox
              uses: actions/checkout@v3
              with:
                  repository: IRIS-Solutions-Team/IRIS-Toolbox
                  ref: ${{ inputs.iris_repo_ref }}
                  fetch-depth: 1
                  path: ./${{ env.IRIS_TOOLBOX_REPO }}
                  token: ${{ secrets.token_with_all_access }}


            - name: Clone workflow repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1
                  path: "./workflow-forecast"
                  token: ${{ secrets.token_with_all_access }}


            - name: Create timestamp and branch name
              id: stamp
              run: |
                  if [[ _${{ inputs.input_data_snapshot_time }} == "_" ]]; then
                      timestamp="$(date -uIseconds)"
                      timestamp="${timestamp/+00:00/}Z"
                  else
                      timestamp=${{ inputs.input_data_snapshot_time }}
                  fi
                  ### forecast_branch_name="forecast-${{ inputs.model_repo }}-$timestamp"
                  ### forecast_branch_name="${forecast_branch_name//:/-}"
                  forecast_branch_name="test-forecast"
                  echo "timestamp=$timestamp" >> $GITHUB_OUTPUT
                  echo "forecast_branch_name=$forecast_branch_name" >> $GITHUB_OUTPUT


            - name: Create main forecast branch on workflow-forecast repo and get its SHA
              id: workflow_forecast_repo
              run: |
                  cd $GITHUB_WORKSPACE/workflow-forecast
                  forecast_branch_name=${{ steps.stamp.outputs.forecast_branch_name }}
                  #
                  git config user.name "${{ env.CI_AUTHOR }}"
                  git config user.email "${{ env.CI_EMAIL }}"
                  #
                  git switch -c "$forecast_branch_name"
                  git push origin "$forecast_branch_name"
                  SHA="$(git rev-parse --short HEAD)"
                  echo "SHA=$SHA" >> $GITHUB_OUTPUT
                  #
                  cd $GITHUB_WORKSPACE


            - name: Prepare artifact
              run: |
                  cd $GITHUB_WORKSPACE
                  #
                  cp -r ./workflow-forecast/artifact ./
                  #
                  cd $GITHUB_WORKSPACE


            - name: Prepare config for local dependencies
              run: |
                  cd $GITHUB_WORKSPACE
                  #
                  CONFIG_FILE=./artifact/config.json
                  echo '{' > $CONFIG_FILE
                  printf '    "forecast-branch-name": "%s",\n' ${{ steps.stamp.outputs.forecast_branch_name }} >> $CONFIG_FILE
                  printf '    "timestamp": "%s",\n' ${{ steps.stamp.outputs.timestamp }} >> $CONFIG_FILE
                  printf '    "dependencies": {\n' >> $CONFIG_FILE
                  cd $GITHUB_WORKSPACE/${{ env.WORKFLOW_FORECAST_REPO }}
                  directory="workflow-forecast"
                  url=$(git remote get-url origin)
                  branch=${{ steps.stamp.outputs.forecast_branch_name }}-ANALYST
                  cd $GITHUB_WORKSPACE
                  printf '        "%s": {"url": "%s", "branch": "%s", "commitish": null},\n' $directory $url $branch >> $CONFIG_FILE
                  for directory in \
                      ${{ env.MODEL_REPO }} \
                      ${{ env.MODEL_INFRA_REPO }} \
                      ${{ env.TOOLSET_REPO }} \
                      ${{ env.DATA_WAREHOUSE_CLIENT_REPO }} \
                      ${{ env.IRIS_TOOLBOX_REPO }} \
                  ; do
                      cd $GITHUB_WORKSPACE/$directory
                      url=$(git remote get-url origin)
                      commitish=$(git rev-parse --short HEAD)
                      cd $GITHUB_WORKSPACE
                  printf '        "%s": {"url": "%s", "branch": null, "commitish": "%s"},\n' $directory $url $commitish >> $CONFIG_FILE
                  done
                  printf '        "end": null\n' >> $CONFIG_FILE
                  printf '    },\n' >> $CONFIG_FILE
                  printf '    "end": null\n' >> $CONFIG_FILE
                  echo '}' >> $CONFIG_FILE
                  #
                  cd $GITHUB_WORKSPACE


            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ steps.stamp.outputs.forecast_branch_name }}
                  path: ./artifact


            - name: Print out config.json
              run: |
                  cat ./artifact/config.json


            - name: Create and commit the ANALYST forecast branch
              run: |
                  cd $GITHUB_WORKSPACE/workflow-forecast
                  #
                  forecast_branch_name=${{ steps.stamp.outputs.forecast_branch_name }}
                  git switch -c "$forecast_branch_name-ANALYST"
                  git push origin "$forecast_branch_name-ANALYST"
                  #
                  cd $GITHUB_WORKSPACE

