name: Run forecast

on:
    workflow_call:
    workflow_dispatch:

jobs:
    run-forecast:
        runs-on: ubuntu-latest

        steps:

            - name: Clone workflow-forecast repo
              uses: actions/checkout@v3
              with:
                fetch-depth: 1
                path: "./workflow-forecast"

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"

            - name: Prepare environment
              run: |
                cd $GITHUB_WORKSPACE
                cp ./workflow-forecast/artifact/*.* .
                python prepare_forecast_environment.py --local=no
                cd $GITHUB_WORKSPACE

