name: Run forecast

on:
    workflow_call:
    workflow_dispatch:

jobs:
    run-forecast:
        runs-on: ubuntu-latest

        steps:

            - name: Clone workflow-forecast repo
              uses: actions/checkout@v3
              with:
                fetch-depth: 1
                path: "./workflow-forecast"

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"

            - name: Install Python dependencies
              run: | 
                cd $GITHUB_WORKSPACE
                pip install -r ./workflow-forecast/requirements.txt

            - name: Prepare environment
              run: |
                cd $GITHUB_WORKSPACE
                echo ===========================================
                cd $GITHUB_WORKSPACE/workflow-forecast
                git status
                git branch
                echo ===========================================
                cd $GITHUB_WORKSPACE
                cp ./workflow-forecast/artifact/*.* ./
                pwd
                ls
                python prepare_forecast_environment.py --local=no
                echo ===========================================
                ls
                echo ===========================================
                cd $GITHUB_WORKSPACE/workflow-forecast
                git status
                git branch
                cd $GITHUB_WORKSPACE

