name: Prepare local forecast package

permissions:
  actions: write

on:
  workflow_dispatch:
    inputs:
      model_repo:
         description: "Country model repo"
         required: true
         type: choice
         options:
           - "Model-US"
           - "Model-EA"
           - "Model-CZ"
      model_repo_ref:
          description: "Country model version"
          required: false
          type: string
          default: ""

jobs:

  prepare_local_environment:
    runs-on: ubuntu-latest
    env:
      CI_AUTHOR: Production workflow
      CI_EMAIL: "noreply@ogresearch.com"
      
    steps:
    
      - name: Clone country model repo
        uses: actions/checkout@v3
        with:
          repository: OGR-EIU/${{ inputs.model_repo }}
          ref: ${{ inputs.model_repo_ref }}
          fetch-depth: 1
          path: ./${{ inputs.model_repo }}
          token: ${{ secrets.token_with_all_access }}
       
      - name: Get SHA of model repo
        id: model_repo
        run: |
          cd $GITHUB_WORKSPACE/${{ inputs.model_repo }}
          SHA="$(git rev-parse --short HEAD)"
          echo "SHA=$SHA" >> $GITHUB_OUTPUT
          cd $GITHUB_WORKSPACE
    
      - name: Clone workflow repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: "./workflow-forecast"
          token: ${{ secrets.token_with_all_access }}

      - name: Config workflow-forecast and get SHA
        id: workflow_forecast_repo
        run: |
          cd $GITHUB_WORKSPACE/workflow-forecast
          git config user.name "${{ env.CI_AUTHOR }}"
          git config user.email "${{ env.CI_EMAIL }}"
          SHA="$(git rev-parse --short HEAD)"
          echo "SHA=$SHA" >> $GITHUB_OUTPUT
          cd $GITHUB_WORKSPACE

      - name: Create timestamp, branch name and the main forecast branch
        id: forecast_branch
        run: |
          cd $GITHUB_WORKSPACE/workflow-forecast
          timestamp="$(date -uIseconds)U"
          forecast_branch_name="forecast-${{ inputs.model_repo }}-$timestamp"
          forecast_branch_name="${forecast_branch_name//:/-}"
          echo "timestamp=$timestamp" >> $GITHUB_OUTPUT
          echo "forecast_branch_name=$forecast_branch_name" >> $GITHUB_OUTPUT
          git switch -c "$forecast_branch_name"
          cd $GITHUB_WORKSPACE

      - name: Commit the main forecast branch
        run: |
          cd $GITHUB_WORKSPACE/workflow-forecast
          #
          cp ./.github/workflows/prepare_local_environment.py ./analyst/prepare_local_environment.py
          #
          forecast_branch_name=${{ steps.forecast_branch.outputs.forecast_branch_name }}
          timestamp=${{ steps.forecast_branch.outputs.timestamp }}
          model_repo=${{ inputs.model_repo }}
          model_repo_SHA=${{ steps.model_repo.outputs.SHA }}
          workflow_forecast_repo="workflow-forecast"
          workflow_forecast_repo_SHA=${{ steps.workflow_forecast_repo.outputs.SHA }}
          echo '{' > ./analyst/config.json
          echo '    "forecast_branch_name": "$forecast_branch_name",' >> ./analyst/config.json
          echo '    "timestamp": "$timestamp",' >> ./analyst/config.json
          echo '    "model_repo": "$model_repo",' >> ./analyst/config.json
          echo '    "model_repo_SHA": "$model_repo_SHA",' >> ./analyst/config.json
          echo '    "workflow_forecast_repo": "$workflow_forecast_repo",' >> ./analyst/config.json
          echo '    "workflow_forecast_repo_SHA": "$workflow_forecast_repo_SHA",' >> ./analyst/config.json
          echo '    "end": ""' >> ./analyst/config.json
          echo '}' >> ./analyst/config.json
          #
          git add ./analyst
          git commit -m "Prepared $forecast_branch_name"
          git push origin "$forecast_branch_name"
          #
          cd $GITHUB_WORKSPACE

      - name: Create and commit the ANALYST forecast branch
        run: |
          cd $GITHUB_WORKSPACE/workflow-forecast
          forecast_branch_name=${{ steps.forecast_branch.outputs.forecast_branch_name }}
          git switch -c "$forecast_branch_name-ANALYST"
          git push origin "$forecast_branch_name-ANALYST"
          cd $GITHUB_WORKSPACE


