name: Prepare local forecast package

on:
  workflow_dispatch:
    inputs:
      model_repo:
         description: "Country model repo"
         required: true
         type: choice
         options:
           - "Model-US"
           - "Model-EA"
           - "Model-CZ"
      model_repo_comittish:
          description: "Country model version"
          required: true
          type: string
          default: "HEAD"

jobs:
  create_local_environment_script:

    runs-on: ubuntu-latest

    steps:
      - name: Clone workflow repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Populate script with input parameters
        run: |
          cp ./.github/workflows/prepare_local_environment.py ./prepare_local_environment.py
          sed -i "s/@(model_repo)/${{ inputs.model_repo }}" ./prepare_local_environment.py
          sed -i "s/@(model_repo_commitish)/${{ inputs.model_repo_commitish }}" ./prepare_local_environment.py


