on:
    workflow_call


jobs:
    create_and_upload_file:
        runs-on: ubuntu-latest

        steps:

            - name: Create file
            - run: |
                echo "123" > file123.txt
                
            - name: Upload artifact
            - uses: actions/upload-artifact@v3
              with:
                  name: art
                  path: file123.txt
